version: "3"

services: 
    redis:
        image: 'redis:alpine'
        container_name: redis
        command: redis-server --requirepass password
        ports:
            - 6379:6379

        environment:
            - REDIS_REPLICATION_MODE=master
